version: "3.8"
services:
  web:
    image: "dunglas/frankenphp"
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - .:/app
    environment:
      - FRANKENPHP_CONFIG="worker ./public/index.php"